"""init

Revision ID: 717c5bbe7539
Revises:
Create Date: 2026-02-15 00:32:21.293968

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

import models  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "717c5bbe7539"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fax", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_definitions",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("table_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_inspection_definitions_name"),
        sa.UniqueConstraint("table_key", name="uq_inspection_definitions_table_key"),
    )
    op.create_table(
        "missions",
        sa.Column("mission_id", models.GUID(length=36), nullable=False),
        sa.Column("permission", sa.String(length=20), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("mission_id"),
    )
    op.create_table(
        "report_templates",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("report_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("last_verified_mtime", sa.Float(), nullable=True),
        sa.Column("sheet_names", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_templates_report_type"),
        "report_templates",
        ["report_type"],
        unique=False,
    )
    op.create_table(
        "inspection_columns",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("inspection_definition_id", models.GUID(length=36), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("column_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("choices", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_definition_id"],
            ["inspection_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inspection_definition_id",
            "column_key",
            name="uq_inspection_columns_definition_column_key",
        ),
    )
    op.create_table(
        "inspection_rows",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("inspection_definition_id", models.GUID(length=36), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("row_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inspection_definition_id"],
            ["inspection_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inspection_definition_id",
            "row_key",
            name="uq_inspection_rows_definition_row_key",
        ),
    )
    op.create_table(
        "instruments",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company_id", models.GUID(length=36), nullable=True),
        sa.Column("model_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "maintenance_cycle", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parts",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("part_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company_id", models.GUID(length=36), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("report_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("report_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("control_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("company_id", models.GUID(length=36), nullable=True),
        sa.Column(
            "internal_control_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("work_location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "overall_judgment", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("work_date_start", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("work_date_end", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("report_snapshot", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workers",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company_id", models.GUID(length=36), nullable=True),
        sa.Column("seal_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mission_reports",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("mission_id", models.GUID(length=36), nullable=False),
        sa.Column("report_id", models.GUID(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.mission_id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mission_reports_mission_id"),
        "mission_reports",
        ["mission_id"],
        unique=False,
    )
    op.create_table(
        "owned_instruments",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("equipment_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "equipment_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "management_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("instrument_id", models.GUID(length=36), nullable=True),
        sa.Column("company_id", models.GUID(length=36), nullable=True),
        sa.Column("cal_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cal_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("instrument_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_clients",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("report_id", models.GUID(length=36), nullable=True),
        sa.Column("company_id", models.GUID(length=36), nullable=True),
        sa.Column("role_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_id", "role_key", name="uq_report_clients_report_role_key"
        ),
    )
    op.create_table(
        "report_workers",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("report_id", models.GUID(length=36), nullable=True),
        sa.Column("worker_id", models.GUID(length=36), nullable=True),
        sa.Column("worker_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_id", "role_key", name="uq_report_workers_report_role_key"
        ),
    )
    op.create_table(
        "target_instruments",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("instrument_id", models.GUID(length=36), nullable=True),
        sa.Column("report_id", models.GUID(length=36), nullable=True),
        sa.Column(
            "manufacturing_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("tag_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("range", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "manufacturing_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "overall_assessment", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("electrode_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detector_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "detector_manufacturing_number",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "used_parts",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("report_id", models.GUID(length=36), nullable=True),
        sa.Column("part_id", models.GUID(length=36), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspection_details",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("inspection_definition_id", models.GUID(length=36), nullable=True),
        sa.Column("inspection_year", sa.Integer(), nullable=True),
        sa.Column("inspection_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_instrument_id", models.GUID(length=36), nullable=True),
        sa.Column("report_id", models.GUID(length=36), nullable=True),
        sa.Column(
            "inspection_start", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("inspection_end", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comments", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("values", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inspection_definition_id"],
            ["inspection_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_instrument_id"],
            ["target_instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instrument_properties",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("target_instrument_id", models.GUID(length=36), nullable=True),
        sa.Column("property_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("property_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_instrument_id"],
            ["target_instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_owned_instruments",
        sa.Column("id", models.GUID(length=36), nullable=False),
        sa.Column("report_id", models.GUID(length=36), nullable=True),
        sa.Column("owned_instrument_id", models.GUID(length=36), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owned_instrument_id"],
            ["owned_instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_owned_instruments")
    op.drop_table("instrument_properties")
    op.drop_table("inspection_details")
    op.drop_table("used_parts")
    op.drop_table("target_instruments")
    op.drop_table("report_workers")
    op.drop_table("report_clients")
    op.drop_table("owned_instruments")
    op.drop_index(op.f("ix_mission_reports_mission_id"), table_name="mission_reports")
    op.drop_table("mission_reports")
    op.drop_table("workers")
    op.drop_table("reports")
    op.drop_table("parts")
    op.drop_table("instruments")
    op.drop_table("inspection_rows")
    op.drop_table("inspection_columns")
    op.drop_index(
        op.f("ix_report_templates_report_type"), table_name="report_templates"
    )
    op.drop_table("report_templates")
    op.drop_table("missions")
    op.drop_table("inspection_definitions")
    op.drop_table("companies")
    # ### end Alembic commands ###
