"""
AUTO-GENERATED by scripts/generate-schema.mjs — DO NOT EDIT.
Source of truth: shared/schema-metadata.json
"""

GENERATED_SYNC_TABLES_META = [
    {
        "table_name": "report_formats",
        "model_class_name": "ReportFormats",
        "is_master": True,
        "items_attr": "report_formats",
    },
    {
        "table_name": "table_definitions",
        "model_class_name": "TableDefinitions",
        "is_master": True,
        "items_attr": "table_definitions",
    },
    {
        "table_name": "schema_definitions",
        "model_class_name": "SchemaDefinitions",
        "is_master": True,
        "items_attr": "schema_definitions",
    },
    {
        "table_name": "companies",
        "model_class_name": "Companies",
        "is_master": True,
        "items_attr": "companies",
    },
    {
        "table_name": "workers",
        "model_class_name": "Workers",
        "is_master": True,
        "items_attr": "workers",
        "parent_resolvers": [("companies", "company_id")],
    },
    {
        "table_name": "instruments",
        "model_class_name": "Instruments",
        "is_master": True,
        "items_attr": "instruments",
        "parent_resolvers": [("companies", "company_id")],
    },
    {
        "table_name": "sites",
        "model_class_name": "Sites",
        "is_master": True,
        "items_attr": "sites",
        "parent_resolvers": [("companies", "company_id")],
    },
    {
        "table_name": "parts",
        "model_class_name": "Parts",
        "is_master": True,
        "items_attr": "parts",
        "parent_resolvers": [("companies", "company_id")],
    },
    {
        "table_name": "owned_instruments",
        "model_class_name": "OwnedInstruments",
        "is_master": True,
        "items_attr": "owned_instruments",
        "parent_resolvers": [
            ("companies", "company_id"),
            ("instruments", "instrument_id"),
        ],
    },
    {
        "table_name": "reports",
        "model_class_name": "Reports",
        "is_master": False,
        "items_attr": "reports",
    },
    {
        "table_name": "report_sites",
        "model_class_name": "ReportSites",
        "is_master": False,
        "items_attr": "report_sites",
        "fk_mappings": {"site_id": "sites"},
        "role_key_prefix": "site",
    },
    {
        "table_name": "report_workers",
        "model_class_name": "ReportWorkers",
        "is_master": False,
        "items_attr": "report_workers",
        "fk_mappings": {"worker_id": "workers"},
        "role_key_prefix": "role",
        "extra_fields_extractor_name": "_worker_role_extra",
    },
    {
        "table_name": "target_instruments",
        "model_class_name": "TargetInstruments",
        "is_master": False,
        "items_attr": "target_instruments",
        "fk_mappings": {
            "instrument_id": "instruments",
            "schema_id": "schema_definitions",
        },
        "extra_fields_extractor_name": "_target_instrument_extra",
        "id_map_key": "target_instruments",
    },
    {
        "table_name": "target_instrument_tables",
        "model_class_name": "TargetInstrumentTables",
        "is_master": False,
        "items_attr": "target_instrument_tables",
        "fk_mappings": {
            "target_instrument_id": "target_instruments",
            "table_definition_id": "table_definitions",
        },
        "extra_fields_extractor_name": "_target_instrument_table_extra",
    },
    {
        "table_name": "used_parts",
        "model_class_name": "UsedParts",
        "is_master": False,
        "items_attr": "used_parts",
        "fk_mappings": {"part_id": "parts"},
        "extra_fields_extractor_name": "_used_part_extra",
    },
    {
        "table_name": "report_owned_instruments",
        "model_class_name": "ReportOwnedInstruments",
        "is_master": False,
        "items_attr": "report_owned_instruments",
        "fk_mappings": {"owned_instrument_id": "owned_instruments"},
    },
    {
        "table_name": "report_clients",
        "model_class_name": "ReportClients",
        "is_master": False,
        "items_attr": "report_clients",
        "fk_mappings": {"company_id": "companies"},
        "role_key_prefix": "client",
    },
]
