/**
 * AUTO-GENERATED by scripts/generate-schema.mjs — DO NOT EDIT.
 * Source of truth: shared/schema-metadata.json
 *
 * Indexes specifically used for initializing standard Dexie database stores.
 */

export const DEXIE_SCHEMA = {
  companies: "id",
  workers: "id, companyId",
  instruments: "id, companyId",
  schemaDefinitions: "id",
  sites: "id, companyId",
  parts: "id, companyId",
  ownedInstruments: "id, companyId, instrumentId",
  tableDefinitions: "id",
  reportFormats: "id",
  reports: "id, companyId, schemaId, controlNumber",
  reportSites: "id, reportId, siteId, sortOrder",
  reportClients: "id, reportId, companyId, sortOrder",
  reportWorkers: "id, reportId, workerId, sortOrder",
  targetInstruments: "id, reportId, instrumentId, sortOrder",
  targetInstrumentTables: "id, targetInstrumentId, tableDefinitionId, reportId, sortOrder",
  usedParts: "id, reportId, partId, sortOrder",
  reportOwnedInstruments: "id, reportId, ownedInstrumentId",
} as const;
