/**
 * AUTO-GENERATED by scripts/generate-schema.mjs — DO NOT EDIT.
 * Source of truth: shared/schema-metadata.json
 */

import type { DatabaseSchema } from "./schema";

export const TABLE_KEYS: (keyof DatabaseSchema)[] = [
  "companies",
  "workers",
  "instruments",
  "schemaDefinitions",
  "sites",
  "parts",
  "ownedInstruments",
  "tableDefinitions",
  "reportFormats",
  "reports",
  "reportSites",
  "reportClients",
  "reportWorkers",
  "targetInstruments",
  "targetInstrumentTables",
  "usedParts",
  "reportOwnedInstruments",
];

export const FOREIGN_KEYS: Partial<
  Record<keyof DatabaseSchema, Record<string, keyof DatabaseSchema>>
> = {
  workers: { companyId: "companies" },
  instruments: { companyId: "companies" },
  sites: { companyId: "companies" },
  parts: { companyId: "companies" },
  ownedInstruments: { companyId: "companies", instrumentId: "instruments" },
  reports: {
    companyId: "companies",
    schemaId: "schemaDefinitions",
    reportFormatId: "reportFormats",
  },
  reportSites: { reportId: "reports", siteId: "sites" },
  reportClients: { reportId: "reports", companyId: "companies" },
  reportWorkers: { reportId: "reports", workerId: "workers" },
  targetInstruments: { reportId: "reports", instrumentId: "instruments" },
  targetInstrumentTables: {
    targetInstrumentId: "targetInstruments",
    tableDefinitionId: "tableDefinitions",
    reportId: "reports",
  },
  usedParts: { reportId: "reports", partId: "parts" },
  reportOwnedInstruments: { reportId: "reports", ownedInstrumentId: "ownedInstruments" },
};

export const TABLE_LABELS: Record<keyof DatabaseSchema, string> = {
  companies: "Companies",
  workers: "Workers",
  instruments: "Instruments",
  schemaDefinitions: "Schema Definitions",
  sites: "Sites",
  parts: "Parts",
  ownedInstruments: "Owned Instruments",
  tableDefinitions: "Table Definitions",
  reportFormats: "Report Formats",
  reports: "Reports",
  reportSites: "Report Sites",
  reportClients: "Report Clients",
  reportWorkers: "Report Workers",
  targetInstruments: "Target Instruments",
  targetInstrumentTables: "Target Instrument Tables",
  usedParts: "Used Parts",
  reportOwnedInstruments: "Report Owned Instruments",
};

export const IMPORT_ORDER: (keyof DatabaseSchema)[] = [
  "reportFormats",
  "tableDefinitions",
  "schemaDefinitions",
  "companies",
  "workers",
  "instruments",
  "sites",
  "parts",
  "ownedInstruments",
  "reports",
  "reportSites",
  "reportWorkers",
  "targetInstruments",
  "targetInstrumentTables",
  "usedParts",
  "reportOwnedInstruments",
  "reportClients",
];
