/**
 * AUTO-GENERATED by scripts/generate-validation.mjs — DO NOT EDIT.
 *
 * Source of truth: shared/validation-rules.json
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars -- re-exported for consumers
export const VALIDATION_RULES = {
  report: {
    reportType: { maxLength: 100 },
    reportTitle: { maxLength: 200, required: true as const },
    controlNumber: { maxLength: 50 },
  },
  company: {
    name: { maxLength: 100, required: true as const },
    department: { maxLength: 100 },
    postalCode: { maxLength: 10 },
    address: { maxLength: 300 },
    phone: { maxLength: 20 },
    fax: { maxLength: 20 },
    email: { maxLength: 100 },
  },
  worker: {
    name: { maxLength: 100, required: true as const },
  },
  instrument: {
    name: { maxLength: 100, required: true as const },
    modelNumber: { maxLength: 100 },
    maintenanceCycle: { maxLength: 50 },
  },
  part: {
    name: { maxLength: 100, required: true as const },
    partNumber: { maxLength: 100 },
  },
  schemaDefinition: {
    targetEntity: { maxLength: 100 },
    version: { maxLength: 50 },
  },
  site: {
    name: { maxLength: 200, required: true as const },
    location: { maxLength: 300 },
    description: { maxLength: 1000 },
  },
  targetInstrument: {
    tagNumber: { maxLength: 100 },
  },
  tableDefinition: {
    name: { maxLength: 100, required: true as const },
  },
  targetInstrumentTable: {
    roleKey: { maxLength: 100 },
  },
} as const;
