#!/usr/bin/env zx
/**
 * shared/schema-metadata.json (SSOT) から以下の3ファイルを自動生成する。
 *   1. packages/types/src/schemaRegistry.generated.ts — スキーマ、ラベル、外部キー、トポロジカルソート済みIMPORT_ORDER
 *   2. apps/scout/src/db/schema.generated.ts — Dexie 用データベースストア定義
 *   3. apps/backend/config/schema_meta.generated.py — 同期構成（SyncTableConfig）メタデータ
 *
 * Usage:
 *   node scripts/generate-schema.mjs
 *   node scripts/generate-schema.mjs --check
 */
import "zx/globals";
import path from "node:path";
import { readFile, writeFile } from "node:fs/promises";
import { execSync } from "node:child_process";
import { getProjectRoot } from "./utils.mjs";

// Toposort function to pre-calculate IMPORT_ORDER during build time
import { toposort } from "./shared/toposort.mjs";

const projectRoot = getProjectRoot(import.meta.url);

const SSOT_PATH = path.join(projectRoot, "shared", "schema-metadata.json");
const TS_OUT = path.join(projectRoot, "packages", "types", "src", "schemaRegistry.generated.ts");
const DEXIE_OUT = path.join(projectRoot, "apps", "scout", "src", "db", "schema.generated.ts");
const PY_OUT = path.join(projectRoot, "apps", "backend", "config", "schema_meta_generated.py");

const isCheck = process.argv.includes("--check");

// ---------- load SSOT ----------
const raw = await readFile(SSOT_PATH, "utf8");
const schemaMeta = JSON.parse(raw);
const tableKeys = Object.keys(schemaMeta);

// Pre-calculate IMPORT_ORDER using toposort
const edges = [];
for (const table of tableKeys) {
  const fk = schemaMeta[table].foreignKeys;
  if (!fk) continue;
  for (const refTable of Object.values(fk)) {
    if (tableKeys.includes(refTable)) {
      // 依存先から依存元へのエッジを張る (refTable -> table)
      // toposort はこれを受け取り refTable が先に、table が後に来るよう並び替える
      edges.push([refTable, table]);
    }
  }
}

// 孤立ノード（外部キーを持たない、かつ誰からも参照されないノード）が消えないよう、
// nodes には明示的に全キーを渡して toposort を呼び出す
const importOrder = toposort(tableKeys, edges);

// ---------- generate TS Types/Registry ----------

function generateTypeScript(meta) {
  const lines = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-schema.mjs — DO NOT EDIT.",
    " * Source of truth: shared/schema-metadata.json",
    " */",
    "",
    'import type { DatabaseSchema } from "./schema";',
    "",
    "export const TABLE_KEYS: (keyof DatabaseSchema)[] = [",
  ];

  for (const key of tableKeys) {
    lines.push(`  "${key}",`);
  }
  lines.push("];", "");

  lines.push(
    "export const FOREIGN_KEYS: Partial<Record<keyof DatabaseSchema, Record<string, keyof DatabaseSchema>>> = {"
  );
  for (const [table, info] of Object.entries(meta)) {
    if (info.foreignKeys) {
      const fkStr = Object.entries(info.foreignKeys)
        .map(([k, v]) => `"${k}": "${v}"`)
        .join(", ");
      lines.push(`  ${table}: { ${fkStr} },`);
    }
  }
  lines.push("};", "");

  lines.push("export const TABLE_LABELS: Record<keyof DatabaseSchema, string> = {");
  for (const [table, info] of Object.entries(meta)) {
    lines.push(`  ${table}: "${info.label}",`);
  }
  lines.push("};", "");

  lines.push("export const IMPORT_ORDER: (keyof DatabaseSchema)[] = [");
  for (const key of importOrder) {
    lines.push(`  "${key}",`);
  }
  lines.push("];", "");

  return lines.join("\n");
}

// ---------- generate Dexie DB Schema ----------

function generateDexie(meta) {
  const lines = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-schema.mjs — DO NOT EDIT.",
    " * Source of truth: shared/schema-metadata.json",
    " *",
    " * Indexes specifically used for initializing standard Dexie database stores.",
    " */",
    "",
    "export const DEXIE_SCHEMA = {",
  ];
  for (const [table, info] of Object.entries(meta)) {
    lines.push(`  ${table}: "${info.dexieIndexes}",`);
  }
  lines.push("} as const;", "");
  return lines.join("\n");
}

// ---------- generate Python Backend Meta ----------

function camelToPascalCase(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function camelToSnakeCase(str) {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function generatePython(meta) {
  const lines = [
    '"""',
    "AUTO-GENERATED by scripts/generate-schema.mjs — DO NOT EDIT.",
    "Source of truth: shared/schema-metadata.json",
    '"""',
    "",
  ];

  lines.push("GENERATED_SYNC_TABLES_META = [");
  for (const table of importOrder) {
    // Maintain dependency order in backend iteration too
    const info = meta[table];
    const isMaster = info.isMaster ? "True" : "False";
    const tableName = camelToSnakeCase(table);
    const modelClass = camelToPascalCase(table); // Roughly, e.g. reportWorkers -> ReportWorkers (Might need manual mapping later if mismatch, but Citadel models match pascal case mostly)

    // Construct dict
    const pyDictStr = [];
    pyDictStr.push(`"table_name": "${tableName}"`);
    pyDictStr.push(`"model_class_name": "${modelClass}"`);
    pyDictStr.push(`"is_master": ${isMaster}`);
    if (info.syncMetaExtras) {
      for (const [k, v] of Object.entries(info.syncMetaExtras)) {
        if (Array.isArray(v) && typeof v[0] === "object") {
          // Handle parent_resolvers [['companies', 'company_id']]
          const arrRepr = "[" + v.map((tup) => `("${tup[0]}", "${tup[1]}")`).join(", ") + "]";
          pyDictStr.push(`"${k}": ${arrRepr}`);
        } else if (typeof v === "object") {
          // Handle dict like fk_mappings {'site_id': 'sites'}
          const dictRepr =
            "{" +
            Object.entries(v)
              .map(([dk, dv]) => `"${dk}": "${dv}"`)
              .join(", ") +
            "}";
          pyDictStr.push(`"${k}": ${dictRepr}`);
        } else if (k === "extra_fields_extractor_name") {
          pyDictStr.push(`"${k}": "${v}"`); // Just store name, bind function in sync_meta.py manually
        } else {
          pyDictStr.push(`"${k}": "${v}"`);
        }
      }
    }

    lines.push(`    {`);
    for (const entry of pyDictStr) {
      lines.push(`        ${entry},`);
    }
    lines.push(`    },`);
  }
  lines.push("]", "");

  return lines.join("\n");
}

// ---------- write or check ----------

const tsContent = generateTypeScript(schemaMeta);
const dexieContent = generateDexie(schemaMeta);
const pyContent = generatePython(schemaMeta);

async function formatFile(filePath, content) {
  const isWin = process.platform === "win32";
  try {
    if (filePath.endsWith(".py")) {
      const venvDir = path.join(projectRoot, "venv");
      const binDir = isWin ? path.join(venvDir, "Scripts") : path.join(venvDir, "bin");
      let ruffPath = path.join(binDir, isWin ? "ruff.exe" : "ruff");

      // Fallback to 'ruff' in PATH if venv ruff is not found
      if (!fs.existsSync(ruffPath)) {
        try {
          execSync(isWin ? "where ruff" : "which ruff", { stdio: "ignore" });
          ruffPath = "ruff";
        } catch {
          ruffPath = null;
        }
      }

      if (ruffPath) {
        const tmpPath = filePath + ".tmp";
        await writeFile(tmpPath, content, "utf8");
        try {
          execSync(`"${ruffPath}" format "${tmpPath}" --quiet`, { stdio: "ignore" });
          const formatted = await readFile(tmpPath, "utf8");
          await fs.promises.unlink(tmpPath);
          return formatted;
        } catch (e) {
          if (fs.existsSync(tmpPath)) await fs.promises.unlink(tmpPath);
          throw e;
        }
      }
    } else if (filePath.endsWith(".ts")) {
      const prettierPath = path.join(
        projectRoot,
        "node_modules",
        ".bin",
        "prettier" + (isWin ? ".cmd" : "")
      );
      if (fs.existsSync(prettierPath)) {
        // Prettier can be slow to start, but for schema generation it's acceptable
        const tmpPath = filePath + ".tmp.ts";
        await writeFile(tmpPath, content, "utf8");
        try {
          execSync(`"${prettierPath}" --write "${tmpPath}" --loglevel warn`, { stdio: "ignore" });
          const formatted = await readFile(tmpPath, "utf8");
          await fs.promises.unlink(tmpPath);
          return formatted;
        } catch (e) {
          if (fs.existsSync(tmpPath)) await fs.promises.unlink(tmpPath);
          throw e;
        }
      }
    }
  } catch (e) {
    console.warn(`Warning: Failed to format ${filePath}: ${e.message}`);
  }
  return content;
}

if (isCheck) {
  let fail = false;
  const checkFile = async (outPath, content) => {
    try {
      const existing = await readFile(outPath, "utf8");
      const formattedContent = await formatFile(outPath, content);

      // Normalize line endings for comparison
      const normalize = (s) => s.replace(/\r\n/g, "\n").trim();

      if (normalize(existing) !== normalize(formattedContent)) {
        console.error(`MISMATCH: ${path.relative(projectRoot, outPath)}`);
        fail = true;
      }
    } catch (e) {
      console.error(`ERROR checking ${path.relative(projectRoot, outPath)}: ${e.message}`);
      fail = true;
    }
  };
  await checkFile(TS_OUT, tsContent);
  await checkFile(DEXIE_OUT, dexieContent);
  await checkFile(PY_OUT, pyContent);
  if (fail) {
    console.error(
      'Schema files are out of sync or not formatted correctly. Run "node scripts/generate-schema.mjs" to fix.'
    );
    process.exit(1);
  }
  console.log("Schema files are up to date.");
} else {
  // Format before writing
  const formattedTs = await formatFile(TS_OUT, tsContent);
  const formattedDexie = await formatFile(DEXIE_OUT, dexieContent);
  const formattedPy = await formatFile(PY_OUT, pyContent);

  await writeFile(TS_OUT, formattedTs, "utf8");
  console.log(`  Generated: ${path.relative(projectRoot, TS_OUT)}`);
  await writeFile(DEXIE_OUT, formattedDexie, "utf8");
  console.log(`  Generated: ${path.relative(projectRoot, DEXIE_OUT)}`);
  await writeFile(PY_OUT, formattedPy, "utf8");
  console.log(`  Generated: ${path.relative(projectRoot, PY_OUT)}`);
}
